type OpcodeEntry = (&'static str, u8, u8, Option<u8>, Option<u8>);

pub(super) const OPCODES: [OpcodeEntry; 256] = [
    ("NOP", 1, 4, None, None),
    ("LXI B,d16", 3, 10, None, None),
    ("STAX B", 1, 7, None, None),
    ("INX B", 1, 5, None, None),
    ("INR B", 1, 5, None, None),
    ("DCR B", 1, 5, None, None),
    ("MVI B,d8", 2, 7, None, None),
    ("RLC", 1, 4, None, None),
    ("", 0, 0, None, None),
    ("DAD B", 1, 10, None, None),
    ("LDAX B", 1, 7, None, None),
    ("DCX B", 1, 5, None, None),
    ("INR C", 1, 5, None, None),
    ("DCR C", 1, 5, None, None),
    ("MVI C,d8", 2, 7, None, None),
    ("RRC", 1, 4, None, None),
    ("", 0, 0, None, None),
    ("LXI D,d16", 3, 10, None, None),
    ("STAX D", 1, 7, None, None),
    ("INX D", 1, 5, None, None),
    ("INR D", 1, 5, None, None),
    ("DCR D", 1, 5, None, None),
    ("MVI D,d8", 2, 7, None, None),
    ("RAL", 1, 4, None, None),
    ("", 0, 0, None, None),
    ("DAD D", 1, 10, None, None),
    ("LDAX D", 1, 7, None, None),
    ("DCX D", 1, 5, None, None),
    ("INR E", 1, 5, None, None),
    ("DCR E", 1, 5, None, None),
    ("MVI E,d8", 2, 7, None, None),
    ("RAR", 1, 4, None, None),
    ("", 0, 0, None, None),
    ("LXI H,d16", 3, 10, None, None),
    ("SHLD a16", 3, 16, None, None),
    ("INX H", 1, 5, None, None),
    ("INR H", 1, 5, None, None),
    ("DCR H", 1, 5, None, None),
    ("MVI H,d8", 2, 7, None, None),
    ("DAA", 1, 4, None, None),
    ("", 0, 0, None, None),
    ("DAD H", 1, 10, None, None),
    ("LHLD a16", 3, 16, None, None),
    ("DCX H", 1, 5, None, None),
    ("INR L", 1, 5, None, None),
    ("DCR L", 1, 5, None, None),
    ("MVI L,d8", 2, 7, None, None),
    ("CMA", 1, 4, None, None),
    ("", 0, 0, None, None),
    ("LXI SP,d16", 3, 10, None, None),
    ("STA a16", 3, 13, None, None),
    ("INX SP", 1, 5, None, None),
    ("INR M", 1, 10, None, None),
    ("DCR M", 1, 10, None, None),
    ("MVI M,d8", 2, 10, None, None),
    ("STC", 1, 4, None, None),
    ("", 0, 0, None, None),
    ("DAD SP", 1, 10, None, None),
    ("LDA a16", 3, 13, None, None),
    ("DCX SP", 1, 5, None, None),
    ("INR A", 1, 5, None, None),
    ("DCR A", 1, 5, None, None),
    ("MVI A,d8", 2, 7, None, None),
    ("CMC", 1, 4, None, None),
    ("MOV B,B", 1, 5, None, None),
    ("MOV B,C", 1, 5, None, None),
    ("MOV B,D", 1, 5, None, None),
    ("MOV B,E", 1, 5, None, None),
    ("MOV B,H", 1, 5, None, None),
    ("MOV B,L", 1, 5, None, None),
    ("MOV B,M", 1, 7, None, None),
    ("MOV B,A", 1, 5, None, None),
    ("MOV C,B", 1, 5, None, None),
    ("MOV C,C", 1, 5, None, None),
    ("MOV C,D", 1, 5, None, None),
    ("MOV C,E", 1, 5, None, None),
    ("MOV C,H", 1, 5, None, None),
    ("MOV C,L", 1, 5, None, None),
    ("MOV C,M", 1, 7, None, None),
    ("MOV C,A", 1, 5, None, None),
    ("MOV D,B", 1, 5, None, None),
    ("MOV D,C", 1, 5, None, None),
    ("MOV D,D", 1, 5, None, None),
    ("MOV D,E", 1, 5, None, None),
    ("MOV D,H", 1, 5, None, None),
    ("MOV D,L", 1, 5, None, None),
    ("MOV D,M", 1, 7, None, None),
    ("MOV D,A", 1, 5, None, None),
    ("MOV E,B", 1, 5, None, None),
    ("MOV E,C", 1, 5, None, None),
    ("MOV E,D", 1, 5, None, None),
    ("MOV E,E", 1, 5, None, None),
    ("MOV E,H", 1, 5, None, None),
    ("MOV E,L", 1, 5, None, None),
    ("MOV E,M", 1, 7, None, None),
    ("MOV E,A", 1, 5, None, None),
    ("MOV H,B", 1, 5, None, None),
    ("MOV H,C", 1, 5, None, None),
    ("MOV H,D", 1, 5, None, None),
    ("MOV H,E", 1, 5, None, None),
    ("MOV H,H", 1, 5, None, None),
    ("MOV H,L", 1, 5, None, None),
    ("MOV H,M", 1, 7, None, None),
    ("MOV H,A", 1, 5, None, None),
    ("MOV L,B", 1, 5, None, None),
    ("MOV L,C", 1, 5, None, None),
    ("MOV L,D", 1, 5, None, None),
    ("MOV L,E", 1, 5, None, None),
    ("MOV L,H", 1, 5, None, None),
    ("MOV L,L", 1, 5, None, None),
    ("MOV L,M", 1, 7, None, None),
    ("MOV L,A", 1, 5, None, None),
    ("MOV M,B", 1, 7, None, None),
    ("MOV M,C", 1, 7, None, None),
    ("MOV M,D", 1, 7, None, None),
    ("MOV M,E", 1, 7, None, None),
    ("MOV M,H", 1, 7, None, None),
    ("MOV M,L", 1, 7, None, None),
    ("HLT", 1, 7, None, None),
    ("MOV M,A", 1, 7, None, None),
    ("MOV A,B", 1, 5, None, None),
    ("MOV A,C", 1, 5, None, None),
    ("MOV A,D", 1, 5, None, None),
    ("MOV A,E", 1, 5, None, None),
    ("MOV A,H", 1, 5, None, None),
    ("MOV A,L", 1, 5, None, None),
    ("MOV A,M", 1, 7, None, None),
    ("MOV A,A", 1, 5, None, None),
    ("ADD B", 1, 4, None, None),
    ("ADD C", 1, 4, None, None),
    ("ADD D", 1, 4, None, None),
    ("ADD E", 1, 4, None, None),
    ("ADD H", 1, 4, None, None),
    ("ADD L", 1, 4, None, None),
    ("ADD M", 1, 7, None, None),
    ("ADD A", 1, 4, None, None),
    ("ADC B", 1, 4, None, None),
    ("ADC C", 1, 4, None, None),
    ("ADC D", 1, 4, None, None),
    ("ADC E", 1, 4, None, None),
    ("ADC H", 1, 4, None, None),
    ("ADC L", 1, 4, None, None),
    ("ADC M", 1, 7, None, None),
    ("ADC A", 1, 4, None, None),
    ("SUB B", 1, 4, None, None),
    ("SUB C", 1, 4, None, None),
    ("SUB D", 1, 4, None, None),
    ("SUB E", 1, 4, None, None),
    ("SUB H", 1, 4, None, None),
    ("SUB L", 1, 4, None, None),
    ("SUB M", 1, 7, None, None),
    ("SUB A", 1, 4, None, None),
    ("SBB B", 1, 4, None, None),
    ("SBB C", 1, 4, None, None),
    ("SBB D", 1, 4, None, None),
    ("SBB E", 1, 4, None, None),
    ("SBB H", 1, 4, None, None),
    ("SBB L", 1, 4, None, None),
    ("SBB M", 1, 7, None, None),
    ("SBB A", 1, 4, None, None),
    ("ANA B", 1, 4, None, None),
    ("ANA C", 1, 4, None, None),
    ("ANA D", 1, 4, None, None),
    ("ANA E", 1, 4, None, None),
    ("ANA H", 1, 4, None, None),
    ("ANA L", 1, 4, None, None),
    ("ANA M", 1, 7, None, None),
    ("ANA A", 1, 4, None, None),
    ("XRA B", 1, 4, None, None),
    ("XRA C", 1, 4, None, None),
    ("XRA D", 1, 4, None, None),
    ("XRA E", 1, 4, None, None),
    ("XRA H", 1, 4, None, None),
    ("XRA L", 1, 4, None, None),
    ("XRA M", 1, 7, None, None),
    ("XRA A", 1, 4, None, None),
    ("ORA B", 1, 4, None, None),
    ("ORA C", 1, 4, None, None),
    ("ORA D", 1, 4, None, None),
    ("ORA E", 1, 4, None, None),
    ("ORA H", 1, 4, None, None),
    ("ORA L", 1, 4, None, None),
    ("ORA M", 1, 7, None, None),
    ("ORA A", 1, 4, None, None),
    ("CMP B", 1, 4, None, None),
    ("CMP C", 1, 4, None, None),
    ("CMP D", 1, 4, None, None),
    ("CMP E", 1, 4, None, None),
    ("CMP H", 1, 4, None, None),
    ("CMP L", 1, 4, None, None),
    ("CMP M", 1, 7, None, None),
    ("CMP A", 1, 4, None, None),
    ("RNZ", 1, 11, Some(5), None),
    ("POP B", 1, 10, None, None),
    ("JNZ a16", 3, 10, Some(10), None),
    ("JMP a16", 3, 10, None, None),
    ("CNZ a16", 3, 17, Some(11), None),
    ("PUSH B", 1, 11, None, None),
    ("ADI d8", 2, 7, None, None),
    ("RST 0", 1, 11, None, None),
    ("RZ", 1, 11, Some(5), None),
    ("RET", 1, 10, None, None),
    ("JZ a16", 3, 10, Some(10), None),
    ("", 0, 0, None, None),
    ("CZ a16", 3, 17, Some(11), None),
    ("CALL a16", 3, 17, None, None),
    ("ACI d8", 2, 7, None, None),
    ("RST 1", 1, 11, None, None),
    ("RNC", 1, 11, Some(5), None),
    ("POP D", 1, 10, None, None),
    ("JNC a16", 3, 10, Some(10), None),
    ("OUT d8", 2, 10, None, None),
    ("CNC a16", 3, 17, Some(11), None),
    ("PUSH D", 1, 11, None, None),
    ("SUI d8", 2, 7, None, None),
    ("RST 2", 1, 11, None, None),
    ("RC", 1, 11, Some(5), None),
    ("", 0, 0, None, None),
    ("JC a16", 3, 10, Some(10), None),
    ("IN d8", 2, 10, None, None),
    ("CC a16", 3, 17, Some(11), None),
    ("", 0, 0, None, None),
    ("SBI d8", 2, 7, None, None),
    ("RST 3", 1, 11, None, None),
    ("RPO", 1, 11, Some(5), None),
    ("POP H", 1, 10, None, None),
    ("JPO a16", 3, 10, Some(10), None),
    ("XTHL", 1, 18, None, None),
    ("CPO a16", 3, 17, Some(11), None),
    ("PUSH H", 1, 11, None, None),
    ("ANI d8", 2, 7, None, None),
    ("RST 4", 1, 11, None, None),
    ("RPE", 1, 11, Some(5), None),
    ("PCHL", 1, 5, None, None),
    ("JPE a16", 3, 10, Some(10), None),
    ("XCHG", 1, 5, None, None),
    ("CPE a16", 3, 17, Some(11), None),
    ("", 0, 0, None, None),
    ("XRI d8", 2, 7, None, None),
    ("RST 5", 1, 11, None, None),
    ("RP", 1, 11, Some(5), None),
    ("POP PSW", 1, 10, None, None),
    ("JP a16", 3, 10, Some(10), None),
    ("DI", 1, 4, None, None),
    ("CP a16", 3, 17, Some(11), None),
    ("PUSH PSW", 1, 11, None, None),
    ("ORI d8", 2, 7, None, None),
    ("RST 6", 1, 11, None, None),
    ("RM", 1, 11, Some(5), None),
    ("SPHL", 1, 5, None, None),
    ("JM a16", 3, 10, Some(10), None),
    ("EI", 1, 4, None, None),
    ("CM a16", 3, 17, Some(11), None),
    ("", 0, 0, None, None),
    ("CPI d8", 2, 7, None, None),
    ("RST 7", 1, 11, None, None),
];
